### ISSUE TITLE
learning factor Alpha

### ISSUE THREAD

**Issue by Gerrit02** [piotrturski/machine-learning-coursera#1]
Hello @piotrturski ,
I have a question about your solution regarding to define the gradiënt for logarith regression (machine learning). (EX2 Week 3 machinge learning logistic regression)

The formular you use to define the gradiënt is:
grad = (X' * (Hx - y)) / m;

But didn't you have to use the learning factor Alpha? Why is Alpha not used here?
In the EX1 example there you have a for loop from 1 to itterations and alpha was defined as 0.1 I think.
But for EX2 there is no for loop at all and also no alpha defined. Can you clarify a litle bit more why this is not the case here. When looking into the course Week 3 of machine learning when defining the gradiënt there is still make use of alpha and different itterations steps?

**Comment by piotrturski** [comment]
hi,

sorry but i don't remember and i don't really have time to investigate it now. plz consult it with your professor / class. also providing links to specific parts of code would have increased your chances as right now i don't even know which lines r u talking about

**Comment by Gerrit02** [comment]
ok tnx, 
I will try to discuss with the professor or class but the problem is we can not submit code. 

Gerrit 


Van: "Piotr Turski" <notifications@github.com> 
Aan: "piotrturski/machine-learning-coursera" <machine-learning-coursera@noreply.github.com> 
Cc: "gerrit stevens2" <gerrit.stevens2@telenet.be>, "Author" <author@noreply.github.com> 
Verzonden: Woensdag 13 december 2017 03:12:41 
Onderwerp: Re: [piotrturski/machine-learning-coursera] learning factor Alpha (#1) 



hi, 

sorry but i don't remember and i don't really have to investigate it now. plz consult it with your professor / class. also providing links to specific parts of code would have increased your chances as right now i don't even know which lines r u talking about
